
    // @ts-nocheck
    /* eslint-disable */
    /* tslint:disable */
    /* prettier-ignore-start */
    /** @jsxRuntime classic */
    /** @jsx createPlasmicElementProxy */
    /** @jsxFrag React.Fragment */
    // This class is auto-generated by Plasmic; please do not edit!
    // Plasmic Project: QijKjBjMCAKhTPs42ygrD
    // Component: E3xhY_9_9e-I
    // plasmic-unformatted
    import * as React from "react";
    
    import * as p from  "@plasmicapp/react-web";
    import {hasVariant, classNames, wrapWithClassName, createPlasmicElementProxy, makeFragment, MultiChoiceArg, SingleBooleanChoiceArg, SingleChoiceArg, pick, omit, useTrigger, StrictProps, deriveRenderOpts, ensureGlobalVariants} from "@plasmicapp/react-web";
    import LinkButton from "..//LinkButton";  // plasmic-import: 9LofeW3xwMYT/component
    
    import {useScreenVariants} from "./PlasmicGlobalVariant__Screen";  // plasmic-import: tfN8nJpaqzO88/globalVariant
  
    
    import "@plasmicapp/react-web/lib/plasmic.css";
    import  "./plasmic__default_style.css"; // plasmic-import: global/defaultcss
    import  "./plasmic_simple_light.css"; // plasmic-import: QijKjBjMCAKhTPs42ygrD/projectcss
    import  "./PlasmicComponentE3XhY99EI.css" // plasmic-import: E3xhY_9_9e-I/css
  
    import SphereIcon from "./PlasmicIcon__Sphere";  // plasmic-import: Y-meyOo4bkS7n/icon
    

    
    export type PlasmicComponentE3XhY99EI__VariantMembers = {
      
    };
    export type PlasmicComponentE3XhY99EI__VariantsArgs = {};
    type VariantPropType = keyof PlasmicComponentE3XhY99EI__VariantsArgs;
    export const PlasmicComponentE3XhY99EI__VariantProps = new Array<VariantPropType>();
  

    
    export type PlasmicComponentE3XhY99EI__ArgsType = {};
    type ArgPropType = keyof PlasmicComponentE3XhY99EI__ArgsType;
    export const PlasmicComponentE3XhY99EI__ArgProps = new Array<ArgPropType>();
  

    export type PlasmicComponentE3XhY99EI__OverridesType = {
    root?: p.Flex<"div">;
textbox?: p.Flex<"input">;
linkButton?: p.Flex<typeof LinkButton>;
svg?: p.Flex<"svg">;
  };

    
    export interface DefaultComponentE3XhY99EIProps {
      
      className?: string;
    }
  

    
    function PlasmicComponentE3XhY99EI__RenderFunc(
      props: {
        variants: PlasmicComponentE3XhY99EI__VariantsArgs,
        args: PlasmicComponentE3XhY99EI__ArgsType
        overrides: PlasmicComponentE3XhY99EI__OverridesType
        forNode?: string
      }
    ) {
      const {variants, args, overrides, forNode} = props;

      
      
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

      return (
        
  <div
    
    data-plasmic-name={"root"}
    data-plasmic-override={overrides.root}
    data-plasmic-root={true}
    data-plasmic-for-node={forNode}
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "root_reset_QijKjBjMCAKhTPs42ygrD", "ComponentE3XhY99EI__root___23TL")}
    
    >
          
  <p.Stack
    as={"div"}
    
    
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "ComponentE3XhY99EI__box__jjLp9")}
    
    >
          
  <div
    
    
    
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "ComponentE3XhY99EI__box__q5Jgr")}
    
    >
          { "Powering your business" }
        </div>
  

  <div
    
    
    
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "ComponentE3XhY99EI__box__g1REc")}
    
    >
          { "Lorem ipsum dolor sit amet consectetur adipisicing elit nemo expedita voluptas culpa sapiente." }
        </div>
  

  <p.Stack
    as={"div"}
    
    
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "ComponentE3XhY99EI__box__mO2Rv")}
    
    >
          
  <input
    
    data-plasmic-name={"textbox"}
    data-plasmic-override={overrides.textbox}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__input", "ComponentE3XhY99EI__textbox__n0Xxx")}
placeholder={("Your email..." as const)}
size={(1 as const)}
type={("text" as const)}
value={("" as const)}
    
    />
  

  <LinkButton
    
    data-plasmic-name={"linkButton"}
    data-plasmic-override={overrides.linkButton}
    
    
    
    className={classNames("__wab_instance", "ComponentE3XhY99EI__linkButton__eybf0")}
text={"Subscribe"}
type={("solidBlue" as const)}
    
    />
  
        </p.Stack>
  

  <div
    
    
    
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "ComponentE3XhY99EI__box__mucbv")}
    
    >
          { "7 days free trial. No credit card required." }
        </div>
  
        </p.Stack>
  
{ (hasVariant(globalVariants, "screen", "mobile") ? false : true) ? (
  <div
    
    
    
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "ComponentE3XhY99EI__box__gwf15")}
    
    >
          
  <SphereIcon
    
    data-plasmic-name={"svg"}
    data-plasmic-override={overrides.svg}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__svg", "ComponentE3XhY99EI__svg__zkR7O")}
role={"img"}
    
    />
  
        </div>
  ) : null }
        </div>
  
      ) as React.ReactElement | null;
    }

    
    const PlasmicDescendants = {
      root: ["root", "textbox", "linkButton", "svg"],
textbox: ["textbox"],
linkButton: ["linkButton"],
svg: ["svg"],
    } as const;
    type NodeNameType = keyof typeof PlasmicDescendants;
    type DescendantsType<T extends NodeNameType> = (typeof PlasmicDescendants)[T][number];
    type NodeDefaultElementType = {
      root: "div";
textbox: "input";
linkButton: typeof LinkButton;
svg: "svg"
    };
  

    
    type ReservedPropsType = "variants" | "args" | "overrides";
    type NodeOverridesType<T extends NodeNameType> = Pick<PlasmicComponentE3XhY99EI__OverridesType, DescendantsType<T>>;
    type NodeComponentProps<T extends NodeNameType> = (
      // Explicitly specify variants, args, and overrides as objects
      & {
        variants?: PlasmicComponentE3XhY99EI__VariantsArgs;
        args?: PlasmicComponentE3XhY99EI__ArgsType;
        overrides?: NodeOverridesType<T>;
      }
      // Specify variants directly as props
      & Omit<PlasmicComponentE3XhY99EI__VariantsArgs, ReservedPropsType>
      // Specify args directly as props
      & Omit<PlasmicComponentE3XhY99EI__ArgsType, ReservedPropsType>
      // Specify overrides for each element directly as props
      & Omit<NodeOverridesType<T>, ReservedPropsType | VariantPropType | ArgPropType>
      // Specify props for the root element
      & Omit<Partial<React.ComponentProps<NodeDefaultElementType[T]>>, ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>>
    );
    function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
      type PropsType = NodeComponentProps<NodeName> & {key?: React.Key};
      const func = function<T extends PropsType>(props: T & StrictProps<T, PropsType>) {
        const {variants, args, overrides} = deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicComponentE3XhY99EI__ArgProps,
          internalVariantPropNames: PlasmicComponentE3XhY99EI__VariantProps,
        });

        return PlasmicComponentE3XhY99EI__RenderFunc({
          variants, args, overrides, forNode: nodeName
        });
      };
      if (nodeName === "root") {
        func.displayName = "PlasmicComponentE3XhY99EI";
      } else {
        func.displayName = `PlasmicComponentE3XhY99EI.${nodeName}`;
      }
      return func;
    }

    export const PlasmicComponentE3XhY99EI = Object.assign(
      // Top-level PlasmicComponentE3XhY99EI renders the root element
      makeNodeComponent("root"),
      {
        // Helper components rendering sub-elements
        textbox: makeNodeComponent("textbox"),
linkButton: makeNodeComponent("linkButton"),
svg: makeNodeComponent("svg"),

        // Metadata about props expected for PlasmicComponentE3XhY99EI
        internalVariantProps: PlasmicComponentE3XhY99EI__VariantProps,
        internalArgProps: PlasmicComponentE3XhY99EI__ArgProps,
      }
    );
  

    export default PlasmicComponentE3XhY99EI;
    /* prettier-ignore-end */
  