
    // @ts-nocheck
    /* eslint-disable */
    /* tslint:disable */
    /* prettier-ignore-start */
    /** @jsxRuntime classic */
    /** @jsx createPlasmicElementProxy */
    /** @jsxFrag React.Fragment */
    // This class is auto-generated by Plasmic; please do not edit!
    // Plasmic Project: QijKjBjMCAKhTPs42ygrD
    // Component: 3yxJ7Ja4Tk
    // plasmic-unformatted
    import * as React from "react";
    
    import * as p from  "@plasmicapp/react-web";
    import {hasVariant, classNames, wrapWithClassName, createPlasmicElementProxy, makeFragment, MultiChoiceArg, SingleBooleanChoiceArg, SingleChoiceArg, pick, omit, useTrigger, StrictProps, deriveRenderOpts, ensureGlobalVariants} from "@plasmicapp/react-web";
    import Header from "..//Header";  // plasmic-import: QyzeFos7Y0jF/component
    
    import {DesktopContext, DesktopValue} from "./PlasmicGlobalVariant__Desktop";  // plasmic-import: JiKdD7wKL4/globalVariant
import {LahjoitaLogoAndMenuPositioningContext, LahjoitaLogoAndMenuPositioningValue} from "./PlasmicGlobalVariant__LahjoitaLogoAndMenuPositioning";  // plasmic-import: t_80StzGnA/globalVariant
  
    
    import "@plasmicapp/react-web/lib/plasmic.css";
    import  "./plasmic__default_style.css"; // plasmic-import: global/defaultcss
    import  "./plasmic_simple_light.css"; // plasmic-import: QijKjBjMCAKhTPs42ygrD/projectcss
    import  "./PlasmicLahjoita.css" // plasmic-import: 3yxJ7Ja4Tk/css
  
    
    

    
    export type PlasmicLahjoita__VariantMembers = {
      
    };
    export type PlasmicLahjoita__VariantsArgs = {};
    type VariantPropType = keyof PlasmicLahjoita__VariantsArgs;
    export const PlasmicLahjoita__VariantProps = new Array<VariantPropType>();
  

    
    export type PlasmicLahjoita__ArgsType = {};
    type ArgPropType = keyof PlasmicLahjoita__ArgsType;
    export const PlasmicLahjoita__ArgProps = new Array<ArgPropType>();
  

    export type PlasmicLahjoita__OverridesType = {
    root?: p.Flex<"div">;
box?: p.Flex<"div">;
header?: p.Flex<typeof Header>;
  };

    
    export interface DefaultLahjoitaProps {
      
      className?: string;
    }
  

    
    function PlasmicLahjoita__RenderFunc(
      props: {
        variants: PlasmicLahjoita__VariantsArgs,
        args: PlasmicLahjoita__ArgsType
        overrides: PlasmicLahjoita__OverridesType
        forNode?: string
      }
    ) {
      const {variants, args, overrides, forNode} = props;

      
      
  const globalVariants = ensureGlobalVariants({
    desktop: React.useContext(DesktopContext),
lahjoitaLogoAndMenuPositioning: React.useContext(LahjoitaLogoAndMenuPositioningContext)
  });

      return (
        <React.Fragment>
    
    
    
      <div className={"plasmic_page_wrapper"}>
        
  <div
    
    data-plasmic-name={"root"}
    data-plasmic-override={overrides.root}
    data-plasmic-root={true}
    data-plasmic-for-node={forNode}
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "root_reset_QijKjBjMCAKhTPs42ygrD", "Lahjoita__root___0KyeC", { "Lahjoita__root__global_desktop___0KyeCxl8Az": hasVariant(globalVariants, "desktop", "desktop"), "Lahjoita__root__global_lahjoitaLogoAndMenuPositioning_unnamedVariant___0KyeC4X3Cv": hasVariant(globalVariants, "lahjoitaLogoAndMenuPositioning", "unnamedVariant") })}
    
    >
          
  <div
    
    data-plasmic-name={"box"}
    data-plasmic-override={overrides.box}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "Lahjoita__box___7SGhy")}
    
    >
          { "Lahjoita" }
        </div>
  

  <Header
    
    data-plasmic-name={"header"}
    data-plasmic-override={overrides.header}
    
    
    
    className={classNames("__wab_instance", "Lahjoita__header__n1Eix", { "Lahjoita__header__global_desktop__n1Eixxl8Az": hasVariant(globalVariants, "desktop", "desktop"), "Lahjoita__header__global_lahjoitaLogoAndMenuPositioning_unnamedVariant__n1Eix4X3Cv": hasVariant(globalVariants, "lahjoitaLogoAndMenuPositioning", "unnamedVariant") })}
    
    />
  
        </div>
  
      </div>
    
  </React.Fragment>
      ) as React.ReactElement | null;
    }

    
    const PlasmicDescendants = {
      root: ["root", "box", "header"],
box: ["box"],
header: ["header"],
    } as const;
    type NodeNameType = keyof typeof PlasmicDescendants;
    type DescendantsType<T extends NodeNameType> = (typeof PlasmicDescendants)[T][number];
    type NodeDefaultElementType = {
      root: "div";
box: "div";
header: typeof Header
    };
  

    
    type ReservedPropsType = "variants" | "args" | "overrides";
    type NodeOverridesType<T extends NodeNameType> = Pick<PlasmicLahjoita__OverridesType, DescendantsType<T>>;
    type NodeComponentProps<T extends NodeNameType> = (
      // Explicitly specify variants, args, and overrides as objects
      & {
        variants?: PlasmicLahjoita__VariantsArgs;
        args?: PlasmicLahjoita__ArgsType;
        overrides?: NodeOverridesType<T>;
      }
      // Specify variants directly as props
      & Omit<PlasmicLahjoita__VariantsArgs, ReservedPropsType>
      // Specify args directly as props
      & Omit<PlasmicLahjoita__ArgsType, ReservedPropsType>
      // Specify overrides for each element directly as props
      & Omit<NodeOverridesType<T>, ReservedPropsType | VariantPropType | ArgPropType>
      // Specify props for the root element
      & Omit<Partial<React.ComponentProps<NodeDefaultElementType[T]>>, ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>>
    );
    function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
      type PropsType = NodeComponentProps<NodeName> & {key?: React.Key};
      const func = function<T extends PropsType>(props: T & StrictProps<T, PropsType>) {
        const {variants, args, overrides} = deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicLahjoita__ArgProps,
          internalVariantPropNames: PlasmicLahjoita__VariantProps,
        });

        return PlasmicLahjoita__RenderFunc({
          variants, args, overrides, forNode: nodeName
        });
      };
      if (nodeName === "root") {
        func.displayName = "PlasmicLahjoita";
      } else {
        func.displayName = `PlasmicLahjoita.${nodeName}`;
      }
      return func;
    }

    export const PlasmicLahjoita = Object.assign(
      // Top-level PlasmicLahjoita renders the root element
      makeNodeComponent("root"),
      {
        // Helper components rendering sub-elements
        box: makeNodeComponent("box"),
header: makeNodeComponent("header"),

        // Metadata about props expected for PlasmicLahjoita
        internalVariantProps: PlasmicLahjoita__VariantProps,
        internalArgProps: PlasmicLahjoita__ArgProps,
      }
    );
  

    export default PlasmicLahjoita;
    /* prettier-ignore-end */
  