
    // @ts-nocheck
    /* eslint-disable */
    /* tslint:disable */
    /* prettier-ignore-start */
    /** @jsxRuntime classic */
    /** @jsx createPlasmicElementProxy */
    /** @jsxFrag React.Fragment */
    // This class is auto-generated by Plasmic; please do not edit!
    // Plasmic Project: QijKjBjMCAKhTPs42ygrD
    // Component: QyzeFos7Y0jF
    // plasmic-unformatted
    import * as React from "react";
    
    import * as p from  "@plasmicapp/react-web";
    import {hasVariant, classNames, wrapWithClassName, createPlasmicElementProxy, makeFragment, MultiChoiceArg, SingleBooleanChoiceArg, SingleChoiceArg, pick, omit, useTrigger, StrictProps, deriveRenderOpts, ensureGlobalVariants} from "@plasmicapp/react-web";
    
    
    import {DesktopContext, DesktopValue} from "./PlasmicGlobalVariant__Desktop";  // plasmic-import: JiKdD7wKL4/globalVariant
import {LahjoitaLogoAndMenuPositioningContext, LahjoitaLogoAndMenuPositioningValue} from "./PlasmicGlobalVariant__LahjoitaLogoAndMenuPositioning";  // plasmic-import: t_80StzGnA/globalVariant
  
    
    import "@plasmicapp/react-web/lib/plasmic.css";
    import  "./plasmic__default_style.css"; // plasmic-import: global/defaultcss
    import  "./plasmic_simple_light.css"; // plasmic-import: QijKjBjMCAKhTPs42ygrD/projectcss
    import  "./PlasmicHeader.css" // plasmic-import: QyzeFos7Y0jF/css
  
    
    

    
    export type PlasmicHeader__VariantMembers = {
      
    };
    export type PlasmicHeader__VariantsArgs = {};
    type VariantPropType = keyof PlasmicHeader__VariantsArgs;
    export const PlasmicHeader__VariantProps = new Array<VariantPropType>();
  

    
    export type PlasmicHeader__ArgsType = {};
    type ArgPropType = keyof PlasmicHeader__ArgsType;
    export const PlasmicHeader__ArgProps = new Array<ArgPropType>();
  

    export type PlasmicHeader__OverridesType = {
    root?: p.Flex<"div">;
img?: p.Flex<"img">;
link?: p.Flex<"a">;
  };

    
    export interface DefaultHeaderProps {
      
      className?: string;
    }
  

    
    function PlasmicHeader__RenderFunc(
      props: {
        variants: PlasmicHeader__VariantsArgs,
        args: PlasmicHeader__ArgsType
        overrides: PlasmicHeader__OverridesType
        forNode?: string
      }
    ) {
      const {variants, args, overrides, forNode} = props;

      
      
  const globalVariants = ensureGlobalVariants({
    desktop: React.useContext(DesktopContext),
lahjoitaLogoAndMenuPositioning: React.useContext(LahjoitaLogoAndMenuPositioningContext)
  });

      return (
        
  <div
    
    data-plasmic-name={"root"}
    data-plasmic-override={overrides.root}
    data-plasmic-root={true}
    data-plasmic-for-node={forNode}
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "root_reset_QijKjBjMCAKhTPs42ygrD", "Header__root__e6WbA")}
    
    >
          
  <img
    
    data-plasmic-name={"img"}
    data-plasmic-override={overrides.img}
    
    
    
    alt={""}
className={classNames("plasmic_default__all", "plasmic_default__img", "Header__img__gLscZ", { "Header__img__global_desktop__gLscZxl8Az": hasVariant(globalVariants, "desktop", "desktop"), "Header__img__global_lahjoitaLogoAndMenuPositioning_unnamedVariant__gLscZ4X3Cv": hasVariant(globalVariants, "lahjoitaLogoAndMenuPositioning", "unnamedVariant") })}
role={"img"}
src={"/image.png"}
    
    />
  

  <a
    
    data-plasmic-name={"link"}
    data-plasmic-override={overrides.link}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__a", "__wab_text", "Header__link___0OEig", { "Header__link__global_lahjoitaLogoAndMenuPositioning_unnamedVariant___0OEig4X3Cv": hasVariant(globalVariants, "lahjoitaLogoAndMenuPositioning", "unnamedVariant") })}
href={("artelokuvaoy.com/koti" as const)}
    
    >
          { "Koti" }
        </a>
  
        </div>
  
      ) as React.ReactElement | null;
    }

    
    const PlasmicDescendants = {
      root: ["root", "img", "link"],
img: ["img"],
link: ["link"],
    } as const;
    type NodeNameType = keyof typeof PlasmicDescendants;
    type DescendantsType<T extends NodeNameType> = (typeof PlasmicDescendants)[T][number];
    type NodeDefaultElementType = {
      root: "div";
img: "img";
link: "a"
    };
  

    
    type ReservedPropsType = "variants" | "args" | "overrides";
    type NodeOverridesType<T extends NodeNameType> = Pick<PlasmicHeader__OverridesType, DescendantsType<T>>;
    type NodeComponentProps<T extends NodeNameType> = (
      // Explicitly specify variants, args, and overrides as objects
      & {
        variants?: PlasmicHeader__VariantsArgs;
        args?: PlasmicHeader__ArgsType;
        overrides?: NodeOverridesType<T>;
      }
      // Specify variants directly as props
      & Omit<PlasmicHeader__VariantsArgs, ReservedPropsType>
      // Specify args directly as props
      & Omit<PlasmicHeader__ArgsType, ReservedPropsType>
      // Specify overrides for each element directly as props
      & Omit<NodeOverridesType<T>, ReservedPropsType | VariantPropType | ArgPropType>
      // Specify props for the root element
      & Omit<Partial<React.ComponentProps<NodeDefaultElementType[T]>>, ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>>
    );
    function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
      type PropsType = NodeComponentProps<NodeName> & {key?: React.Key};
      const func = function<T extends PropsType>(props: T & StrictProps<T, PropsType>) {
        const {variants, args, overrides} = deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHeader__ArgProps,
          internalVariantPropNames: PlasmicHeader__VariantProps,
        });

        return PlasmicHeader__RenderFunc({
          variants, args, overrides, forNode: nodeName
        });
      };
      if (nodeName === "root") {
        func.displayName = "PlasmicHeader";
      } else {
        func.displayName = `PlasmicHeader.${nodeName}`;
      }
      return func;
    }

    export const PlasmicHeader = Object.assign(
      // Top-level PlasmicHeader renders the root element
      makeNodeComponent("root"),
      {
        // Helper components rendering sub-elements
        img: makeNodeComponent("img"),
link: makeNodeComponent("link"),

        // Metadata about props expected for PlasmicHeader
        internalVariantProps: PlasmicHeader__VariantProps,
        internalArgProps: PlasmicHeader__ArgProps,
      }
    );
  

    export default PlasmicHeader;
    /* prettier-ignore-end */
  