
    // @ts-nocheck
    /* eslint-disable */
    /* tslint:disable */
    /* prettier-ignore-start */
    /** @jsxRuntime classic */
    /** @jsx createPlasmicElementProxy */
    /** @jsxFrag React.Fragment */
    // This class is auto-generated by Plasmic; please do not edit!
    // Plasmic Project: QijKjBjMCAKhTPs42ygrD
    // Component: Njo910sC96l4
    // plasmic-unformatted
    import * as React from "react";
    
    import * as p from  "@plasmicapp/react-web";
    import {hasVariant, classNames, wrapWithClassName, createPlasmicElementProxy, makeFragment, MultiChoiceArg, SingleBooleanChoiceArg, SingleChoiceArg, pick, omit, useTrigger, StrictProps, deriveRenderOpts, ensureGlobalVariants} from "@plasmicapp/react-web";
    
    
    import {LahjoitaThingContext, LahjoitaThingValue} from "./PlasmicGlobalVariant__LahjoitaThing";  // plasmic-import: g7Y8HDtKUW/globalVariant
  
    
    import "@plasmicapp/react-web/lib/plasmic.css";
    import  "./plasmic__default_style.css"; // plasmic-import: global/defaultcss
    import  "./plasmic_simple_light.css"; // plasmic-import: QijKjBjMCAKhTPs42ygrD/projectcss
    import  "./PlasmicTopSection.css" // plasmic-import: Njo910sC96l4/css
  
    
    

    
    export type PlasmicTopSection__VariantMembers = {
      
    };
    export type PlasmicTopSection__VariantsArgs = {};
    type VariantPropType = keyof PlasmicTopSection__VariantsArgs;
    export const PlasmicTopSection__VariantProps = new Array<VariantPropType>();
  

    
    export type PlasmicTopSection__ArgsType = {};
    type ArgPropType = keyof PlasmicTopSection__ArgsType;
    export const PlasmicTopSection__ArgProps = new Array<ArgPropType>();
  

    export type PlasmicTopSection__OverridesType = {
    root?: p.Flex<"div">;
  };

    
    export interface DefaultTopSectionProps {
      
      className?: string;
    }
  

    
    function PlasmicTopSection__RenderFunc(
      props: {
        variants: PlasmicTopSection__VariantsArgs,
        args: PlasmicTopSection__ArgsType
        overrides: PlasmicTopSection__OverridesType
        forNode?: string
      }
    ) {
      const {variants, args, overrides, forNode} = props;

      
      
  const globalVariants = ensureGlobalVariants({
    lahjoitaThing: React.useContext(LahjoitaThingContext)
  });

      return (
        
  <div
    
    data-plasmic-name={"root"}
    data-plasmic-override={overrides.root}
    data-plasmic-root={true}
    data-plasmic-for-node={forNode}
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "root_reset_QijKjBjMCAKhTPs42ygrD", "TopSection__root__s7MSk")}
    
    >
          
  <p.Stack
    as={"div"}
    
    
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "TopSection__box__kqd4Q")}
    
    >
          
  <p.Stack
    as={"div"}
    
    
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "TopSection__box__mxjr7")}
    
    >
          
  <div
    
    
    
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "TopSection__box__rcgYc")}
    
    >
          
  <div
    
    
    
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "TopSection__box__tSqZi", { "TopSection__box__global_lahjoitaThing_unnamedVariant__tSqZiYktPe": hasVariant(globalVariants, "lahjoitaThing", "unnamedVariant") })}
    
    >
          { hasVariant(globalVariants, "lahjoitaThing", "unnamedVariant") ? "Lahjoita\n" : "Art Elokuva OY" }
        </div>
  
        </div>
  
        </p.Stack>
  
        </p.Stack>
  

  <div
    
    
    
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "TopSection__box__spcTa", { "TopSection__box__global_lahjoitaThing_unnamedVariant__spcTaYktPe": hasVariant(globalVariants, "lahjoitaThing", "unnamedVariant") })}
    
    >
          { hasVariant(globalVariants, "lahjoitaThing", "unnamedVariant") ? "Täältä voit lahjoitaa rahaa meille että me voidaan jatkaa tämän hyvän contentin tekemistä.\n\n" : "\nTervetuloa Art Elokuva OY:n nettisivuille!\n\nTietoja\nArt Elokuva OY on ryhmä jotka tekevät videoita. Kaikki videomme tulee meidän  YouTube kanavalle.\n\nVideot\nKatso Art Elokuva OY:n uusimpia videoita.\n\nLahjoita\nLahjoita rahaa Art Elokuva OY:lle.\n\nPelit\nKäy katsomassa mitä pelejä olemme tehneet.\n" }
        </div>
  
        </div>
  
      ) as React.ReactElement | null;
    }

    
    const PlasmicDescendants = {
      root: ["root"],
    } as const;
    type NodeNameType = keyof typeof PlasmicDescendants;
    type DescendantsType<T extends NodeNameType> = (typeof PlasmicDescendants)[T][number];
    type NodeDefaultElementType = {
      root: "div"
    };
  

    
    type ReservedPropsType = "variants" | "args" | "overrides";
    type NodeOverridesType<T extends NodeNameType> = Pick<PlasmicTopSection__OverridesType, DescendantsType<T>>;
    type NodeComponentProps<T extends NodeNameType> = (
      // Explicitly specify variants, args, and overrides as objects
      & {
        variants?: PlasmicTopSection__VariantsArgs;
        args?: PlasmicTopSection__ArgsType;
        overrides?: NodeOverridesType<T>;
      }
      // Specify variants directly as props
      & Omit<PlasmicTopSection__VariantsArgs, ReservedPropsType>
      // Specify args directly as props
      & Omit<PlasmicTopSection__ArgsType, ReservedPropsType>
      // Specify overrides for each element directly as props
      & Omit<NodeOverridesType<T>, ReservedPropsType | VariantPropType | ArgPropType>
      // Specify props for the root element
      & Omit<Partial<React.ComponentProps<NodeDefaultElementType[T]>>, ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>>
    );
    function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
      type PropsType = NodeComponentProps<NodeName> & {key?: React.Key};
      const func = function<T extends PropsType>(props: T & StrictProps<T, PropsType>) {
        const {variants, args, overrides} = deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicTopSection__ArgProps,
          internalVariantPropNames: PlasmicTopSection__VariantProps,
        });

        return PlasmicTopSection__RenderFunc({
          variants, args, overrides, forNode: nodeName
        });
      };
      if (nodeName === "root") {
        func.displayName = "PlasmicTopSection";
      } else {
        func.displayName = `PlasmicTopSection.${nodeName}`;
      }
      return func;
    }

    export const PlasmicTopSection = Object.assign(
      // Top-level PlasmicTopSection renders the root element
      makeNodeComponent("root"),
      {
        // Helper components rendering sub-elements
        

        // Metadata about props expected for PlasmicTopSection
        internalVariantProps: PlasmicTopSection__VariantProps,
        internalArgProps: PlasmicTopSection__ArgProps,
      }
    );
  

    export default PlasmicTopSection;
    /* prettier-ignore-end */
  